package_format_version = '1'
module_code = 'PR_PRIORITY_FLORA'
module_version = '1.0.0'
min_geonature_version = '2.0.0'
max_geonature_version = '2.0.0'
exclude_geonature_versions = [ '2.0.1', '2.0.3' ]
